name: 22MCC20166

on:
  push:
    branches: ["master"]
  pull_request: 
    branches: ["master"]
  workflow_dispatch: 
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - run: 
          echo "This is my manual workflow build. "
